# Generated by Django 3.2.5 on 2023-01-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='numero',
            field=models.CharField(max_length=16),
        ),
    ]
