# Generated by Django 3.2.5 on 2023-01-12 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('sobrenome', models.CharField(blank=True, max_length=120, null=True)),
                ('telefone', models.CharField(max_length=17)),
                ('sobre', models.CharField(blank=True, max_length=400, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.categoria')),
            ],
        ),
    ]
